on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: codeberg-tiny
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4
      - name: Setup Typst
        uses: https://github.com/typst-community/setup-typst@v4
        with:
          token: ${{ secrets.GH_API_TOKEN }}
      - name: Build
        run: ./build.sh
      - name: Publish
        uses: https://code.forgejo.org/actions/forgejo-release@v2
        with:
          url: "https://codeberg.org"
          repo: "arslee07/notes"
          tag: latest
          token: ${{ secrets.RELEASE_TOKEN }}
          direction: upload
          release-dir: build
          hide-archive-link: true
          override: true
